<!--NOTEBOOK_HEADER-->
*This notebook contains material from [CBE60499](https://ndcbe.github.io/CBE60499);
content is available [on Github](git@github.com:ndcbe/CBE60499.git).*


<!--NAVIGATION-->
< [3.7 Globalization with Trust Region](https://ndcbe.github.io/CBE60499/03.07-Trust-Region.html) | [Contents](toc.html) | [Tag Index](tag_index.html) | [3.9 Algorithms Homework 2](https://ndcbe.github.io/CBE60499/03.09-Algorithms2.html) ><p><a href="https://colab.research.google.com/github/ndcbe/CBE60499/blob/master/docs/03.08-Algorithms1.ipynb"> <img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a><p><a href="https://ndcbe.github.io/CBE60499/03.08-Algorithms1.ipynb"> <img align="left" src="https://img.shields.io/badge/Github-Download-blue.svg" alt="Download" title="Download Notebook"></a>

# 3.8 Algorithms Homework 1

In [14]:
# Load required Python libraries.
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg

## 3.8.1 Linear Algebra Review

### 3.8.1.1 Exact solution

Solve the following system of linear equations BY HAND with exact arithmetic:

$$3 x_1 + 2 x_2 + x_3 = 6$$
$$-x_1 + 4 x_2 + 5x_3 = 8$$
$$2x_1 -8 x_2 + 10 x_3 = 4$$

Turn in your work via Gradescope.

### 3.8.1.2 Solve using the inverse

Solve the same linear system by first inverting the matrix A and performing matrix multiplication. You should use Python and SciPy.
* Tutorials and documentation: https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html

In [15]:
# Start Solution
A = np.mat('[3 2 1;-1 4 5;2 -8 10]')
A

matrix([[ 3,  2,  1],
        [-1,  4,  5],
        [ 2, -8, 10]])

In [16]:
b = np.mat('[6;8;4]')
b

matrix([[6],
        [8],
        [4]])

In [17]:
x = np.array(linalg.inv(A).dot(b))
print('x1 = {}\nx2 = {}\nx3 = {}'.format(x[0][0],x[1][0],x[2][0]))

x1 = 0.9999999999999998
x2 = 1.0
x3 = 1.0


### 3.8.1.3 Solve using LU decomposition

Do the following:
1. Use ``linalg.lu(A)`` to calculate $P$, $L$, and $U$.
2. Write a function to solve any linear system given the factorization and $b$. You may not use ```linalg.solve``` in your function. Instead, you should write loops to implement back substitution.
3. Use your function to solve the linear system.


In [18]:
# You need to define the matrix A1 somewhere (or change the variable name)
P, L, U = linalg.lu(A)

# Permutation matrix
print(P)

# Lower diagonal matrix
print(L)

# Upper diagonal matrix
print(U)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [-0.33333333 -0.5         1.        ]]
[[ 3.          2.          1.        ]
 [ 0.         -9.33333333  9.33333333]
 [ 0.          0.         10.        ]]


Tip: We discussed this algorithm in class. First write pseudocode on paper (how to translate our notes into loops, logical statements, etc.?). Once you are happy with the logic, code it up.

In [19]:
# Write function here.
def my_lu_solve(P, L, U, b, LOUD=True):
    ''' 
    Solves linear system Ax = b given PLU decomposition of A
    
    Arguments:
        P - N by N permutation matrix
        L - N by N lower triangular matrix with 1 on diagonal
        U - N by N upper triangular matrix
        b - N by 1 vector
    
    Returns:
        x - N by 1 solution to linear system
    '''
    
    # Define x so this does not give an error. You can delete the line below.
    
    # Start solution
    N = len(b)
    y = np.mat(np.zeros((N,1)))
    x = np.mat(np.zeros((N,1)))
    
    rhs1 = P.T.dot(b)
    
    for i in range(N):
        y[i] = (rhs1[i]-L[i][0:i].dot(y[:i]))/L[i][i]
    
    x[-1] = y[-1]/U[-1][-1]
    for i in range(2,N+1):
        x[-i] = (y[-i]-U[-i][-i+1:].dot(x[-i+1:]))/U[-i][-i]
    
    if LOUD:
        print(np.array2string(x))
        
    
    
    
    return x

In [20]:
x = my_lu_solve(P, L, U, b, LOUD=True)

[[1.]
 [1.]
 [1.]]


### 3.8.1.4 Solve using `linalg.solve`


In [21]:
# Start solution
x = linalg.solve(A,b)
print(np.array2string(x))

[[1.]
 [1.]
 [1.]]


## 3.8.2 Eigenvalues

### 3.8.2.1 Calculate eigenvalues by hand (on paper)

Calculate the eigenvalues for the following matrix:

$$
A = \begin{bmatrix} 0 & -4 & -6 \\ -1 & 0 & -3 \\ 1 & 2 & 5 \end{bmatrix}
$$

You may need to do this for a small system on an exam to characterize stationary points of an optimization problem. Hence I would like you to practice at least once on the homework.

### 3.8.2.2 Calculate eigenvalues using `linalg.eig`

Calculate the eigenvalues and corresponding (right) eigenvectors.

In [22]:
# Begin Solution
A = np.mat('0 -4 -6;-1 0 -3;1 2 5')
l, v = linalg.eig(A)
print("Eigenvalues = ",l,"\n")
print("Eigenvectors = \n",v,"\n")

Eigenvalues =  [1.+0.j 2.+0.j 2.+0.j] 

Eigenvectors = 
 [[-0.81649658 -0.0111458   0.90265832]
 [-0.40824829 -0.8302799   0.1523847 ]
 [ 0.40824829  0.5572352  -0.40247591]] 



In [23]:
# YOUR SOLUTION HERE

### 3.8.2.3 Definiteness

Based on your calculations above, is this matrix
1. positive definite
2. positive semi definite
3. negative definite
4. negative semi definite
5. indefinite or
6. cannot say without additional calculations?

Briefly comment to justify your answer.

*Note*: In this class, "briefly comment" means write a few sentences, sketch a picture, write an equation or some combination... whichever you feel is necessary to succinctly provide justification.

### 3.8.2.4 Singular Value Decomposition

**TODO:** Make this a separate problem (after the assignment is turned in this year).

### 3.8.2.5 SVD calculation using `linalg.svd`

Calculate the singular value decomposition of the following matrix using `linalg.svd`:

$$
A_3 = \begin{bmatrix} 1 & 2 & 0 & -1 \\ 2 & 4 & 10^{-6} & -2 \\ 0 & 2 & -1 & 10^{-3} \end{bmatrix}
$$

In [24]:
# Start solution
A3 = np.mat("1 2 0 -1;2 4 1e-6 -2;0 2 -1 1e-3")
U3, S3, Vh3 = linalg.svd(A3)
print("U = \n",U3,"\n")
print("S = \n",S3,"\n")
print("Vh = \n",Vh3,"\n")

U = 
 [[-4.25830830e-01  1.36631105e-01 -8.94427217e-01]
 [-8.51661650e-01  2.73262656e-01  4.47213544e-01]
 [-3.05516837e-01 -9.52186674e-01  1.91553449e-07]] 

S = 
 [5.73316009e+00 1.45975216e+00 3.38134101e-07] 

Vh = 
 [[-3.71375314e-01 -8.49329490e-01  5.32892822e-02  3.71322025e-01]
 [ 4.67994798e-01 -3.68597169e-01  6.52293569e-01 -4.68647091e-01]
 [-3.77573248e-01  3.77856348e-01  7.56090836e-01  3.78139751e-01]
 [ 7.07460026e-01 -3.53376990e-04 -7.08908571e-10  7.06753272e-01]] 



### 3.8.2.6 Condition number
What is the condition number of the matrix? Calculate it two ways:
1. Using SVD results
2. Using ``np.linalg.cond()``

In [25]:
cnumber1 = max(S3)/min(S3)
print("The condition number based on SVD results is ",cnumber1)

The condition number based on SVD results is  16955285.118358795


In [26]:
cnumber2 = np.linalg.cond(A3)
print("The condition number from numpy is ",cnumber2)

The condition number from numpy is  16955285.11835879


### 3.8.2.7 Linear system

Consider the linear system $A_4 \cdot x = b$ with $b = [1, 0, 3]^T$ and

$$
A_4 = \begin{bmatrix} 1 & 2 & 0 \\ 2 & 4 & 10^{-1} \\ 0 & 2 & -1 \end{bmatrix} ~.
$$

Approximately how much uncertainty $||\Delta b||_2$ can you tolerate if you want the uncertainty $||\Delta x||_2$ to be less than $10^{-2}$?


In [27]:
A4 = np.mat('1 2 0;2 4 0.1;0 2 -1')
b4 = np.mat('1;0;3')
x4 = linalg.solve(A4,b4)
x4norm = linalg.norm(x4)
b4norm = linalg.norm(b4)
kappa4 = np.linalg.cond(A4)
unc_x = 0.01
unc_b = unc_x/x4norm*b4norm/kappa4
unc_b


6.160694598769965e-06

**Answer**:  A maximum uncertainty of 6.16e-6 can be tolerated.

### 3.8.2.8 Make it singular


Do/answer the following:
1. Propose a change to a single entry in $A_4$ to make it singular.
2. What are the singular values and condition number after this change?
3. What can you say about the solution to $A_4 \cdot x=b$ after the change?

In [41]:
A4[1,2] = 0
U4, S4, Vh4 = linalg.svd(A4)
print("U = \n",U4,"\n")
print("S = \n",S4,"\n")
print("Vh = \n",Vh4,"\n")
print("The condition number is ",np.linalg.cond(A4))

U = 
 [[-4.17774579e-01  1.59575690e-01  8.94427191e-01]
 [-8.35549159e-01  3.19151379e-01 -4.47213595e-01]
 [-3.56822090e-01 -9.34172359e-01  2.22044605e-16]] 

S = 
 [5.33070426e+00 1.25840857e+00 1.48029737e-16] 

Vh = 
 [[-0.39185683 -0.91758795  0.06693714]
 [ 0.63403768 -0.21661313  0.74234424]
 [ 0.66666667 -0.33333333 -0.66666667]] 

The condition number is  3.6011036551455308e+16


**Answer:**

Replace the 0.1 entry with 0 to make A4 singular.  The singular values and condition number are shown above and the solution does not exist.

## 3.8.3 Convexity

Please turn in via Gradescope.

### 3.8.3.1 Determine if the following functions are convex

1. $x^2 + ax + b, ~x \in \mathbb{R}$
2. $x^3, ~x \in \mathbb{R}$
3. $| x |, ~ x \in [ -5, 5]$
4. $x + y, ~ x \in \mathbb{R}, ~ y \in \mathbb{R}$
5. $x \cdot y, ~ x \in \mathbb{R}, ~ y \in \mathbb{R}$
6. $\log(x), ~ x \in (0,1]$

### 3.8.3.2 Prove the following properties

Consider twice differentiable function $f(x): \mathbb{R}^n \rightarrow \mathbb{R}$.

Recall that $f(x)$ is convex on $x \in \mathbb{R}^n$ if and only if

$f(x+p) \geq f(x) + \nabla f(x)^T p$ for all $x, p \in \mathbb{R}^n$


#### 3.8.3.2.1 PSD implies Convexity

Prove that if $\nabla^2 f(x)$ is positive semidefinite for all $x \in \mathbb{R}^n$, then $f(x)$ must be convex.


#### 3.8.3.2.2 Convexity implies PSD

Prove that if $f(x)$ is convex then $\nabla^2 f(x)$ must be positive semidefinite.

#### 3.8.3.2.3 PD implies Strictly Convex

Prove that if $\nabla^2 f(x)$ is positive definite for all $x \in \mathbb{R}^n$, then $f(x)$ must be strictly convex.

<!--NAVIGATION-->
< [3.7 Globalization with Trust Region](https://ndcbe.github.io/CBE60499/03.07-Trust-Region.html) | [Contents](toc.html) | [Tag Index](tag_index.html) | [3.9 Algorithms Homework 2](https://ndcbe.github.io/CBE60499/03.09-Algorithms2.html) ><p><a href="https://colab.research.google.com/github/ndcbe/CBE60499/blob/master/docs/03.08-Algorithms1.ipynb"> <img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a><p><a href="https://ndcbe.github.io/CBE60499/03.08-Algorithms1.ipynb"> <img align="left" src="https://img.shields.io/badge/Github-Download-blue.svg" alt="Download" title="Download Notebook"></a>